id: I17338BBE
default_language: en
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:32:50.081651
last_modified: 2023-01-04 11:32:50.081667
source_metadata:
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
bases:
  ECAA:
    title: The Prayer in Six Vajra Lines
    base_file: ECAA.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
